name: corefit_academy
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  google_fonts: ^2.2.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  units_converter: ^1.1.1+2
  provider: ^6.0.2
  flutterfire_ui: ^0.3.2
  google_sign_in: ^5.2.3
  font_awesome_flutter: ^10.0.0
  numberpicker: ^2.1.1
  duration_picker: ^1.1.0+1
  flutter_material_pickers: ^3.1.2
  multiple_stream_builder: ^2.0.0
  flutter_slidable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
