// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9m7bqdgKflHBHjK54XzXX34wcUmnFM3U',
    appId: '1:265698258465:web:a6d9608cf1d7cfa98c3d60',
    messagingSenderId: '265698258465',
    projectId: 'corefit-academy',
    authDomain: 'corefit-academy.firebaseapp.com',
    storageBucket: 'corefit-academy.appspot.com',
    measurementId: 'G-QTYWSNZEWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjpYALDGitOcge2CPNsgtvfjfVbWT6d84',
    appId: '1:265698258465:android:63d6981c69735ab88c3d60',
    messagingSenderId: '265698258465',
    projectId: 'corefit-academy',
    storageBucket: 'corefit-academy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuCF2LPn1vm6NgrIRMVRIi9ZpMwT57t9o',
    appId: '1:265698258465:ios:c7432875d60b10068c3d60',
    messagingSenderId: '265698258465',
    projectId: 'corefit-academy',
    storageBucket: 'corefit-academy.appspot.com',
    iosClientId: '265698258465-citah9bdshi2bbj9r9bpffsil352bvjd.apps.googleusercontent.com',
    iosBundleId: 'com.corefitacademy.corefitAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuCF2LPn1vm6NgrIRMVRIi9ZpMwT57t9o',
    appId: '1:265698258465:ios:c7432875d60b10068c3d60',
    messagingSenderId: '265698258465',
    projectId: 'corefit-academy',
    storageBucket: 'corefit-academy.appspot.com',
    iosClientId: '265698258465-citah9bdshi2bbj9r9bpffsil352bvjd.apps.googleusercontent.com',
    iosBundleId: 'com.corefitacademy.corefitAcademy',
  );
}
